### ISSUE TITLE
[PATCH] Compilation issue 'lib' does not exist

### ISSUE THREAD

**Issue by domi007** [silentsignal/burp-pdml#1]
I could have sent a pull request, but I'm too lazy, sorry.
So if anybody has the error message `build.xml:12 lib does not exist` when trying to build the plugin just modify `build.xml` the following way:

Original:

```
        <target name="classes">
                <mkdir dir="build"/>
                <javac srcdir="src:api" destdir="build" includeantruntime="false">
                        <classpath>
                                <fileset dir="lib">
                                        <include name="**/*.jar"/>
                                </fileset>
                        </classpath>
                </javac>
        </target>
```

Fixed:

```
        <target name="classes">
                <mkdir dir="build"/>
                <javac srcdir="src:api" destdir="build" includeantruntime="false">
                </javac>
        </target>
```

So basically you need to remove the inclusion of jars in the lib folder, since there is no need for libs for this simple plugin to be built.

**Comment by dnet** [comment]
Nice catch, thanks! I really did copy-paste another one of my Burp extensions and removed everything from `lib` since as you correctly mention, there are none used in this project. However, [Git cannot track empty directories](https://www.google.com/search?q=git+empty+directories) so this resulted in a silent difference between my working directory and anyone else trying to clone the repository.
